#!/usr/bin/env python3
"""
Challenge Hunter AI v2.2 — Auto-Deploy (no git binary required)
Pushes built code to GitHub using only the GitHub REST API (no subprocess git).
"""

from __future__ import annotations

import base64
import json
import os
import re
import shutil
import sqlite3
import subprocess
import time
from datetime import datetime
from typing import Any, Dict, List, Optional

import requests

from config import DB_PATH, GITHUB_TOKEN, GITHUB_USERNAME, PROJECTS_DIR


# =============================================================================
# GitHub API helpers (no git binary needed)
# =============================================================================

def _gh_headers() -> Dict[str, str]:
    return {
        'Authorization': f'token {GITHUB_TOKEN}',
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
    }


def _github_request(method: str, url: str, **kwargs) -> Dict[str, Any]:
    if not GITHUB_TOKEN or not GITHUB_USERNAME:
        return {'error': 'no_github_credentials',
                'message': 'GITHUB_TOKEN and GITHUB_USERNAME must be set'}
    try:
        r = requests.request(
            method, url,
            headers=_gh_headers(),
            timeout=30,
            **kwargs
        )
        if r.status_code >= 400:
            return {
                'error': f'github_{r.status_code}',
                'message': r.text[:500],
                'status': r.status_code,
            }
        return r.json() if r.text else {}
    except Exception as e:
        return {'error': 'request_failed', 'message': str(e)}


def _create_repo_via_api(repo_name: str, description: str = '') -> Dict[str, Any]:
    """Create a GitHub repo via API. Returns {ok, url, error}."""
    # Check if it already exists
    check = _github_request('GET', f'https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}')
    if 'error' not in check:
        return {'ok': True, 'url': check.get('html_url', ''), 'exists': True}

    result = _github_request(
        'POST', 'https://api.github.com/user/repos',
        json={
            'name': repo_name,
            'description': description[:200] or f'Generated by Challenge Hunter AI',
            'private': False,
            'auto_init': True,  # creates with empty README
        }
    )
    if 'error' in result:
        return {'ok': False, 'error': result.get('message', str(result))[:500]}
    return {'ok': True, 'url': result.get('html_url', ''), 'exists': False}


def _push_files_via_api(repo_name: str, source_dir: str,
                        commit_message: str = 'Initial commit from Challenge Hunter AI') -> Dict[str, Any]:
    """
    Push all files in source_dir to GitHub via the Contents API.
    This works WITHOUT the git binary.
    """
    if not os.path.isdir(source_dir):
        return {'ok': False, 'error': f'Source dir not found: {source_dir}'}

    # Collect all files
    files_to_upload = []
    for root, dirs, filenames in os.walk(source_dir):
        # Skip unwanted directories
        dirs[:] = [d for d in dirs if d not in ('.git', 'node_modules', '__pycache__', '.venv', 'venv', 'dist', 'build', '.next')]
        for fn in filenames:
            # Skip large/binary files
            if fn.endswith(('.pyc', '.so', '.dll', '.exe', '.bin', '.jpg', '.png', '.gif', '.zip', '.tar', '.gz')):
                continue
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, source_dir).replace('\\', '/')
            # Skip files > 1MB (GitHub Contents API limit)
            try:
                if os.path.getsize(full) > 1024 * 1024:
                    continue
            except OSError:
                continue
            try:
                with open(full, 'rb') as f:
                    content = f.read()
                # GitHub Contents API needs base64
                content_b64 = base64.b64encode(content).decode('ascii')
                files_to_upload.append({
                    'path': rel,
                    'content_b64': content_b64,
                })
            except Exception as e:
                print(f"⚠️  skip {rel}: {e}")
                continue

    if not files_to_upload:
        return {'ok': False, 'error': 'no_files_to_upload'}

    # Get the default branch SHA (usually 'main' or 'master')
    repo_info = _github_request('GET', f'https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}')
    if 'error' in repo_info:
        return {'ok': False, 'error': f'repo not found: {repo_info.get("message", "")}'}
    default_branch = repo_info.get('default_branch', 'main')
    branch_url = f'https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}/branches/{default_branch}'

    # Upload files one by one using the Contents API
    uploaded = 0
    failed = []
    for f in files_to_upload:
        result = _github_request(
            'PUT',
            f'https://api.github.com/repos/{GITHUB_USERNAME}/{repo_name}/contents/{f["path"]}',
            json={
                'message': commit_message,
                'content': f['content_b64'],
                'branch': default_branch,
            }
        )
        if 'error' in result:
            failed.append((f['path'], result.get('message', '')[:200]))
        else:
            uploaded += 1

    if uploaded == 0 and failed:
        return {
            'ok': False,
            'error': f'all uploads failed: {failed[:3]}',
            'uploaded': 0,
            'failed': failed,
        }

    return {
        'ok': True,
        'uploaded': uploaded,
        'failed': failed[:5],
        'total_files': len(files_to_upload),
    }


def push_to_github(source_dir: str, repo_name: str) -> Optional[str]:
    """
    High-level: create repo (if needed), push all files, return GitHub URL.
    Uses GitHub API only — no git binary required.
    """
    if not GITHUB_TOKEN or not GITHUB_USERNAME:
        print("⚠️  GITHUB_TOKEN or GITHUB_USERNAME not set")
        return None

    # Sanitize repo name
    safe_name = re.sub(r'[^a-z0-9-]', '-', repo_name.lower())[:50].strip('-')
    if not safe_name:
        safe_name = f"ch-{int(time.time())}"
    safe_name = safe_name.lower()

    # Create the repo
    repo_result = _create_repo_via_api(safe_name, description=f'Generated by Challenge Hunter AI — {repo_name}')
    if not repo_result.get('ok'):
        print(f"⚠️  repo create failed: {repo_result.get('error', 'unknown')[:200]}")
        return None
    url = repo_result['url']
    print(f"📁 Repo: {url}")

    # Push files
    push_result = _push_files_via_api(safe_name, source_dir)
    if not push_result.get('ok'):
        print(f"⚠️  push failed: {push_result.get('error', 'unknown')[:200]}")
        # Still return the URL — repo was created
        return url

    print(f"✅ Pushed {push_result['uploaded']}/{push_result['total_files']} files to {url}")
    return url


# =============================================================================
# Railway deployment
# =============================================================================

def deploy_to_railway(project_id: str, service_name: str, source_dir: str) -> Dict[str, Any]:
    if not os.path.isdir(source_dir):
        return {'success': False, 'error': f'Source dir not found: {source_dir}'}

    token = os.environ.get('RAILWAY_TOKEN', '')
    project = project_id or os.environ.get('RAILWAY_PROJECT_ID', '')
    if not token or not project:
        return {
            'success': False,
            'error': 'missing_credentials',
            'message': 'Set RAILWAY_TOKEN and RAILWAY_PROJECT_ID env vars',
        }

    gh_url = push_to_github(source_dir, service_name)
    if not gh_url:
        return {'success': False, 'error': 'github_push_failed'}

    return {
        'success': True,
        'service_name': service_name,
        'github_url': gh_url,
        'message': 'Code pushed to GitHub. Use Railway dashboard to link the repo for auto-deploy.',
    }


# =============================================================================
# Vercel deployment (unchanged)
# =============================================================================

def deploy_to_vercel(source_dir: str, project_name: str) -> Dict[str, Any]:
    token = os.environ.get('VERCEL_TOKEN', '')
    if not token:
        return {'success': False, 'error': 'no_vercel_token'}

    import tarfile
    import io
    tar_buffer = io.BytesIO()
    with tarfile.open(fileobj=tar_buffer, mode='w:gz') as tar:
        tar.add(source_dir, arcname='.')
    tar_buffer.seek(0)

    try:
        r = requests.post(
            'https://api.vercel.com/v13/deployments',
            headers={'Authorization': f'Bearer {token}', 'Content-Type': 'application/tar'},
            data=tar_buffer.read(),
            params={'name': project_name, 'target': 'production'},
            timeout=120
        )
        r.raise_for_status()
        d = r.json()
        return {'success': True, 'deployment_id': d.get('id'), 'url': d.get('url'),
                'inspect_url': d.get('inspectorUrl')}
    except Exception as e:
        return {'success': False, 'error': str(e)}


# =============================================================================
# Universal deploy
# =============================================================================

def deploy_project(opportunity_id: int) -> Dict[str, Any]:
    base = PROJECTS_DIR
    candidates = []
    if os.path.isdir(base):
        for d in os.listdir(base):
            full = os.path.join(base, d)
            if (os.path.isdir(full) and d.startswith(f"{opportunity_id:04d}_")
                    and d.endswith('_built')):
                candidates.append(full)
    if not candidates:
        return {'success': False, 'error': 'no_built_project_found',
                'hint': 'Run Build Now first to generate the project files'}

    source_dir = max(candidates, key=os.path.getmtime)
    project_name = os.path.basename(source_dir).replace(f"{opportunity_id:04d}_", '').replace('_built', '')

    # Try Railway first
    railway_project_id = os.environ.get('RAILWAY_PROJECT_ID', '')
    if os.environ.get('RAILWAY_TOKEN') and railway_project_id:
        result = deploy_to_railway(railway_project_id, project_name, source_dir)
        result['platform'] = 'railway'
        _record_deployment(opportunity_id, 'railway', result)
        return result

    # Try Vercel
    if os.environ.get('VERCEL_TOKEN'):
        result = deploy_to_vercel(source_dir, project_name)
        result['platform'] = 'vercel'
        _record_deployment(opportunity_id, 'vercel', result)
        return result

    # GitHub only
    gh_url = push_to_github(source_dir, project_name)
    if gh_url:
        result = {
            'success': True,
            'platform': 'github_only',
            'github_url': gh_url,
            'message': 'Code pushed to GitHub. Link the repo to Railway/Vercel manually for live deploy.',
        }
        _record_deployment(opportunity_id, 'github', result)
        return result

    return {
        'success': False,
        'error': 'no_deployment_credentials',
        'message': 'Set GITHUB_TOKEN + GITHUB_USERNAME (and optionally RAILWAY_TOKEN, VERCEL_TOKEN)',
    }


def _record_deployment(opp_id: int, platform: str, result: Dict[str, Any]) -> None:
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO deployments (
                opportunity_id, platform, service_id, deploy_url, status, build_log, deployed_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            opp_id, platform,
            result.get('service_id', ''),
            result.get('url') or result.get('railway_dashboard') or result.get('github_url', ''),
            'live' if result.get('success') else 'failed',
            json.dumps(result)[:4000],
            datetime.now().isoformat() if result.get('success') else None,
        ))
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"⚠️  deploy log failed: {e}")


# =============================================================================
# CLI
# =============================================================================

if __name__ == '__main__':
    import sys
    if len(sys.argv) < 2:
        print("Usage: python deployer.py <opportunity_id>")
        sys.exit(1)
    opp_id = int(sys.argv[1])
    result = deploy_project(opp_id)
    print(json.dumps(result, indent=2, default=str)[:2000])
